number =[1,2,3,4,5,6,7,8,9]
number.append(10)
print(number)
number.remove(4)
print(number)
print(number.count(3))
number.reverse()
print(number)
number.sort()
print(number)
number.pop()
print(number)
print(number.index(3))
number.clear()
print(number)